#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba8) uniform writeonly image2D outputImage;

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    float red = float(pixelCoords.x) / float(imageSize(outputImage).x);
    float blue = float(pixelCoords.y) / float(imageSize(outputImage).y);
    imageStore(outputImage, pixelCoords, vec4(red, 0.5, blue, 1.0));
}